/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Edges, useGLTF } from '@react-three/drei'
import * as THREE from "three";


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/anime2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials.Material} position={[-0.04, -0.01, -0.12]} rotation={[Math.PI / 2, 0, 0]} >
      <meshToonMaterial color={0xdebe97} side={THREE.DoubleSide}/>
      </mesh>
      <mesh castShadow  receiveShadow geometry={nodes.skirt.geometry} material={materials['Material.001']} position={[-0.04, -0.01, -0.12]} rotation={[Math.PI / 2, 0, 0]} >
      <meshToonMaterial color={0x97dec9} side={THREE.DoubleSide}/>

      </mesh>
      <mesh  castShadow receiveShadow geometry={nodes.top.geometry} material={materials.Material} position={[-0.04, -0.01, -0.12]} rotation={[Math.PI / 2, 0, 0]} >
      <meshToonMaterial color={0x97dec9} side={THREE.DoubleSide}/>

      </mesh>
      <mesh castShadow  receiveShadow geometry={nodes.hair.geometry} material={materials.Material} position={[-0.04, -0.01, -0.12]} rotation={[Math.PI / 2, 0, 0]} >
      <meshToonMaterial color={0x87672f} side={THREE.DoubleSide}/>
      {/* <Edges /> */}
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.shoes.geometry} material={materials.Material} position={[-0.04, -0.01, -0.12]} rotation={[Math.PI / 2, 0, 0]} >
      <meshToonMaterial color={0x97dec9} side={THREE.DoubleSide}/>

      </mesh>
    </group>
  )
}

useGLTF.preload('/anime2.glb')
