/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Edges, useGLTF } from '@react-three/drei'
import * as THREE from "three";


export default function Anime2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/anime2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.female001.geometry} material={materials.Material} position={[-0.04, -0.01, -0.12]} rotation={[Math.PI / 2, 0, 0]} >
      <meshToonMaterial color={0xb06f9e} side={THREE.DoubleSide}/>
      {/* <Edges scale={1.0} /> */}

        </mesh>
    </group>
  )
}

useGLTF.preload('/anime2.glb')
