/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Anime({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/anime1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Anime_Female_Base_Mesh.geometry} material={materials.wire_177028149} rotation={[Math.PI / 2, 0, 0]} scale={0.15} />
    </group>
  )
}

useGLTF.preload('/anime1.glb')
