/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HKU Student 3035341 (https://sketchfab.com/eyalunya)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hku-art-module-estofado-90f2138d61a4469ca278e38da62f372f
title: HKU Art Module - Estofado
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Chartest({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/chartest/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} rotation={[0.0, -Math.PI / 2, 0]} scale={[0.1,0.1,0.1]} position={[0.0 ,0.0, -4.0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.86, 2.06, -2.35]} rotation={[-1.07, 0.77, 1.83]}>
            <mesh geometry={nodes.pCube13_FadoBowAndClothesTexture_0.geometry} material={materials.FadoBowAndClothesTexture} />
            <mesh geometry={nodes.pCube14_FadoBowAndClothesTexture_0.geometry} material={materials.FadoBowAndClothesTexture} />
          </group>
          <group position={[-0.39, -0.47, -0.36]} rotation={[-0.48, -1.03, -0.39]}>
            <mesh geometry={nodes.polySurface12_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
            <mesh geometry={nodes.pCube17_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
            <mesh geometry={nodes.pCube18_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
            <mesh geometry={nodes.pCube20_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
          </group>
          <mesh geometry={nodes.polySurface7_FadoBowAndClothesTexture1_0.geometry} material={materials.FadoBowAndClothesTexture1} />
          <mesh geometry={nodes.polySurface8_FadoHairBottleQuiverTexture1_0.geometry} material={materials.FadoHairBottleQuiverTexture1} />
          <mesh geometry={nodes.polySurface9_FadoBowAndClothesTexture1_0.geometry} material={materials.FadoBowAndClothesTexture1} />
          <mesh geometry={nodes.pCube12_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
          <mesh geometry={nodes.polySurface10_NakedFadoTexture1_0.geometry} material={materials.NakedFadoTexture1} />
          <mesh geometry={nodes.pCube15_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
          <mesh geometry={nodes.pCube16_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
          <mesh geometry={nodes.polySurface11_FadoHairBottleQuiverTexture_0.geometry} material={materials.FadoHairBottleQuiverTexture} />
          <mesh geometry={nodes.pPlane21_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane22_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane23_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane24_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane25_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane26_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane27_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane28_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane29_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane30_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane31_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane32_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane33_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane34_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane35_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane36_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane37_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane38_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane39_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane40_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pCube19_LastMinuteDetailsTexture_0.geometry} material={materials.LastMinuteDetailsTexture} />
          <mesh geometry={nodes.pPlane101_lambert7_0.geometry} material={materials.lambert7} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chartest/scene.gltf')
