/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: codyseibert (https://sketchfab.com/codyseibert)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laptop-9a960986f0cc49f99a0afdfb486ec859
title: Laptop
*/

import React, { useRef } from 'react'
import { Edges, useGLTF } from '@react-three/drei'

export default function Laptop({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/laptop/scene.gltf')
  console.log(materials)
  materials.Material.userData = {
    outlineParameters : {}
  }
  materials.Material.userData.outlineParameters = {
  	thickness: 0.01,
 	color: [ 1, 0, 0 ],
 	alpha: 0.0,
 	visible: true,
 	keepAlive: true
  };

  return (
    <group ref={group} {...props} dispose={null} scale={[0.05,0.05,0.05]}  position={[-0.35, 0.23, -4.5]} rotation={[0, 2.90,0]}>
        <group position={[-0.36, 0.57, 0]} rotation={[-Math.PI/2.0, 1.56, -Math.PI]} scale={[-0.03, 0.03, 0.03]}>
          <mesh castShadow geometry={nodes.computer_0.geometry} material={materials.Material} >
        <Edges scale={1.0} />
        </mesh>
        </group>
    </group>
  )
}

useGLTF.preload('/laptop/scene.gltf')
