/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import React, { useEffect, useRef } from 'react'
import { Edges, useGLTF } from '@react-three/drei'

export default function PalmTree({ pos = -2.0, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/palm_tree.glb')

  useEffect(() =>{
    console.log(group.current)
    group.current.position.z = pos;
    //group.current.scale = new THREE.Vector3(0.1,0.1,0.1)
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow recieveShadow scale={[0.05, 0.05, 0.05]} geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} >
        <meshToonMaterial color={0x917060}/>
        {/* <Edges threshold={6} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/palm_tree.glb')
